# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.9'

#      - name: Fix Import Order
#        run: |
#          go install github.com/daixiang0/gci@latest
#          chmod +x ./hack/scripts/fix-import-order.sh
#          make fix-import-order ;

#      - name: Run Go linter
#        uses: golangci/golangci-lint-action@v6
#        with:
#          version: v1.64.5

      - name: Test
        run: |
          chmod +x ./hack/scripts/run_test.sh
          make go-test ;
